name: Deploy to Firebase

on:
  workflow_dispatch:
    branches: [ master ]
    inputs:
      release_notes:
        description: 'Release notes for this version'
        required: true

jobs:
  config_and_sign_bundle:
    name: Configure and Sign Bundle
    uses: ./.github/workflows/config_and_sign_bundle.yml
    secrets: inherit
    with:
      extract_secrets: true
      extract_release_notes: true
      build_release_aab: true
      sign_release_aab: true

  deploy_to_firebase:
    name: Deploy to Firebase
    needs: config_and_sign_bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Download Release Notes
        uses: actions/download-artifact@v4
        with:
          name: release-notes
          path: .

      - name: Download Local Properties
        uses: actions/download-artifact@v4
        with:
          name: local-properties
          path: .

      - name: Read Release Notes
        id: read_notes
        run: echo "RELEASE_NOTES=$(cat whatsnew/whatsnew-en-US.txt)" >> $GITHUB_ENV

      - name: Download Signed AAB
        uses: actions/download-artifact@v4
        with:
          name: signed-aab
          path: .

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: dev
          file: app/build/outputs/bundle/release/app-release.aab
          releaseNotes: ${{ inputs.release_notes }}