name: Deploy to Playstore

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      release-notes:
        description: 'Release notes for this version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Extract secrets
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase ${{ secrets.PASSPHRASE }} \
          --output secrets.tar secrets.gpg 
          tar xvf secrets.tar

      - name: Extract release notes
        run: |
          if [ -s whatsnew/whatsnew-en-US.txt ]; then
            echo -e "\n- ${{ github.event.inputs.release-notes }}" >> whatsnew/whatsnew-en-US.txt
          else
            echo "- ${{ github.event.inputs.release-notes }}" >> whatsnew/whatsnew-en-US.txt
          fi

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Sign Release AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: tech.ericwathome.currencybuddy
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.9
          whatsNewDirectory: whatsnew/
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/build/intermediates/merged_native_libs/release/out/lib
