name: Deploy to Playstore

on:
  workflow_dispatch:
    branches: [ master ]
    inputs:
      release-notes:
        description: 'Release notes for this version'
        required: true

jobs:
  config_and_sign_bundle:
    name: Configure and Sign Bundle
    uses: ./.github/workflows/config_and_sign_bundle.yml
    secrets: inherit
    with:
      extract_secrets: true
      extract_release_notes: true
      release-notes: ${{ github.event.inputs.release_notes }}
      build_release_aab: true
      sign_release_aab: true
      upload_mapping_file: true

  deploy_to_google_play:
    needs: config_and_sign_bundle
    name: Deploy to Google Play
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Download Release Notes
        uses: actions/download-artifact@v4
        with:
          name: release-notes
          path: .

      - name: Download Local Properties
        uses: actions/download-artifact@v4
        with:
          name: local-properties
          path: .

      - name: Read Release Notes
        id: read_notes
        run: echo "RELEASE_NOTES=$(cat whatsnew/whatsnew-en-US.txt)" >> $GITHUB_ENV

      - name: Download Signed AAB
        uses: actions/download-artifact@v4
        with:
          name: signed-aab
          path: release

      - name: Download mapping file
        uses: actions/download-artifact@v4
        with:
          name: mapping-file
          path: mapping

      - name: Download Debug Symbols (conditionally)
        uses: actions/download-artifact@v4
        with:
          name: debug-symbols
          path: debug-symbols

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: tech.ericwathome.currencybuddy
          releaseFiles: release/app-release.aab
          track: production
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.9
          whatsNewDirectory: whatsnew/
          mappingFile: mapping/mapping.txt
          debugSymbols: debug-symbols
