name: Run quality checks

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  quality_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Create google-services.json file
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Inject API secrets
        run: |
          echo "API_KEY=${{secrets.API_KEY }}" >> local.properties
          echo "CONVERTER_BASE_URL=${{secrets.CONVERTER_BASE_URL }}" >> local.properties
          echo "CURRENCY_DETAILS_URL=${{secrets.CURRENCY_DETAILS_URL }}" >> local.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Lint checks
        run: ./gradlew ktlintCheck