name: Run quality checks

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:
  config:
    name: Configure and Sign Bundle
    uses: ./.github/workflows/config_and_sign_bundle.yml
    secrets: inherit
    with:
      create_google_json: true

  quality_checks:
    needs: config
    name: Run Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Download Google Services JSON
        uses: actions/download-artifact@v4
        with:
          name: google-services-json

      - name: Download Local Properties
        uses: actions/download-artifact@v4
        with:
          name: local-properties
          path: .

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Lint checks
        run: ./gradlew ktlintCheck