name: Deploy to Playstore

on:
  workflow_dispatch:
    branches:
      - main
    environment:
      release-notes:
        required: true
        description: 'Release notes for the new version'
        name: Release Notes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Extract secrets
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase ${{ secrets.PASSPHRASE }} \
          --output secrets.tar secrets.gpg 
          tar xvf secrets.tar

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Sign Release AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: tech.ericwathome.currencybuddy
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.9
          whatsNewDirectory: whatsnew/
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/build/intermediates/merged_native_libs/release/out/lib
